"""Topic lists used for large-scale research paper collection."""

LARGE_SCALE_TOPICS = [
    "open source large language models",
    "instruction tuned large language models",
    "parameter efficient fine tuning for language models",
    "LoRA fine tuning for transformer models",
    "adapter tuning for large language models",
    "prompt tuning for transformer language models",
    "QLoRA for efficient language model fine tuning",
    "domain adaptation of large language models",
    "large language models for scientific text",
    "large language models for academic writing",
    "large language models for literature review generation",
    "large language models for scientific question answering",
    "large language models for document summarization",
    "large language models for technical explanation",
    "large language models for knowledge intensive tasks",
    "hallucination detection in large language models",
    "hallucination mitigation in large language models",
    "factuality evaluation of language models",
    "trustworthy large language models",
    "faithfulness in text generation",
    "retrieval augmented generation",
    "retrieval augmented generation for question answering",
    "retrieval augmented generation for literature review",
    "retrieval augmented generation for scientific documents",
    "retrieval augmented generation for academic search",
    "retrieval augmented generation evaluation",
    "RAG hallucination mitigation",
    "citation grounded text generation",
    "evidence grounded generation",
    "grounded question answering",
    "dense retrieval for open domain question answering",
    "dense retrieval for scientific documents",
    "hybrid retrieval for RAG systems",
    "semantic search for scholarly papers",
    "semantic search for research paper exploration",
    "neural information retrieval for scholarly search",
    "academic paper recommendation using embeddings",
    "scientific document retrieval",
    "scientific paper recommendation systems",
    "citation recommendation using neural networks",
    "transformer models for natural language processing",
    "attention mechanisms in transformers",
    "efficient transformer architectures",
    "long context transformers",
    "long document understanding with transformers",
    "transformers for document summarization",
    "transformers for scientific summarization",
    "transformers for question answering",
    "encoder decoder transformer models",
    "text to text transfer transformers",
    "scientific paper summarization",
    "multi document scientific summarization",
    "abstract summarization using transformers",
    "extractive summarization of scientific documents",
    "abstractive summarization of research papers",
    "literature review automation",
    "automatic literature survey generation",
    "research gap detection using AI",
    "research trend analysis using NLP",
    "scientific knowledge graph construction",
    "citation network analysis using machine learning",
    "bibliometric analysis using natural language processing",
    "multi agent systems for research automation",
    "multi agent retrieval augmented generation",
    "agentic workflows for large language models",
    "multi agent collaboration with large language models",
    "autonomous research assistants",
    "AI research assistants for scientific discovery",
    "AI chatbots for education",
    "research assistant chatbots",
    "conversational AI for scientific knowledge discovery",
    "chatbots for scholarly information retrieval",
    "intelligent tutoring systems using large language models",
    "explainable AI for language models",
    "explainable neural networks in NLP",
    "neural networks for natural language understanding",
    "deep learning for document ranking",
    "neural semantic similarity",
    "sentence embeddings for information retrieval",
    "contrastive learning for text embeddings",
    "transformer based embedding models",
    "evaluation metrics for text generation",
    "BLEU ROUGE BERTScore evaluation",
    "automatic evaluation of summarization",
    "human evaluation of generated text",
    "guardrails for large language models",
    "safety guardrails for AI chatbots",
    "retrieval grounding for safe generation",
    "source attribution in generated text",
    "citation aware language models",
    "scientific claim verification",
    "fact checking with retrieval augmented generation",
    "knowledge graph augmented language models",
    "scholarly document understanding",
    "academic search engines using neural retrieval",
    "machine learning for scientific literature mining",
    "natural language processing for scientific text",
]
